spring.application.name=config-server
server.port=8081
#spring.cloud.config.server.git.uri=file:///D:/Courses/BackEnd/Spring/Sb/User_Management_System/local-config
spring.cloud.config.server.git.uri=https://github.com/User-Org-Management/config-repo.git
spring.cloud.config.server.git.username=mostafa-toaima
spring.cloud.config.server.git.password=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
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

